Raise repair
LBHackney-IT/repairs-api-dotnet pull request #11
Opened 2021-01-08 11:55 UTC by kylealexanderhackney

## Link to ticket

https://trello.com/c/fHHnSJXg/280-as-a-user-i-need-to-be-able-to-raise-a-works-order-so-that-contractors-know-what-to-fix

## Describe this PR

### *What is the problem we're trying to solve*

A new endpoint for raising repairs. post a hact complaient raiserepair schema and data will be stored in the repairs db

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

2021-01-11 13:01 UTC, pixeltrix reviewed
Do we want to do the renaming from V1 to V2 in this PR or leave it for a different PR?

2021-01-11 13:18 UTC, josh-dadswell-hackney requested changes

2021-01-11 13:18 UTC, josh-dadswell-hackney commented on RepairsApi/V1/Factories/DBModelFactory.cs
> +            if (raiseRepair.Amount.Count != 1) throw new NotSupportedException("Multiple amounts is not supported");
Probably needs specific test

2021-01-11 13:30 UTC, kylealexanderhackney commented
> Do we want to do the renaming from V1 to V2 in this PR or leave it for a different PR?

We decided to do it after this PR because the change involves renaming a folder which would cause all the files to be marked as moved. This with the some of the larger changes could make git think we deleted and added resulting in a loss of what changes happened

2021-01-11 17:02 UTC, josh-dadswell-hackney approved these changes

2021-01-12 10:50 UTC, pixeltrix approved these changes

2021-01-12 10:51 UTC, LBHBomotoso commented on HactGenerator/SchemaGeneration/SchemaGeneration/Program.cs
> +﻿using Newtonsoft.Json;
What does this class do?

2021-01-12 10:53 UTC, josh-dadswell-hackney commented on HactGenerator/SchemaGeneration/SchemaGeneration/Program.cs
> +﻿using Newtonsoft.Json;
This is a seperate project that generates the ViewModels (/V1/Generated/https://github.com/LBHackney-IT/repairs-api-dotnet/pull/11.cs) based on the HACT spec.

2021-01-12 10:58 UTC, LBHBomotoso commented on RepairsApi/V1/Infrastructure/AlertRegardingLocation.cs
> +    public class AlertRegardingLocation
Could this be Address instead of Location?

2021-01-12 10:59 UTC, LBHBomotoso commented on RepairsApi/V1/Infrastructure/RateScheduleItem.cs
> +        public M3NHFScheduleOfRatesCodeC0 M3NHFSORCode { get; set; }
I've called this ScheduleOfRatesCodes in my migration.

2021-01-12 11:01 UTC, josh-dadswell-hackney commented on RepairsApi/V1/Infrastructure/RateScheduleItem.cs
> +        public M3NHFScheduleOfRatesCodeC0 M3NHFSORCode { get; set; }
Is that migration in flight or already merged?

2021-01-12 11:01 UTC, kylealexanderhackney commented on RepairsApi/V1/Infrastructure/AlertRegardingLocation.cs
> +    public class AlertRegardingLocation
These properties are defined as part of the hact specification. we dont really have much say in the names

2021-01-12 11:01 UTC, LBHBomotoso commented on RepairsApi/V1/Generated/RaiseRepair-M3SoR-v7.cs
>          public string DescriptionOfWork { get; set; }
Are these generated files used?

2021-01-12 11:02 UTC, kylealexanderhackney commented on RepairsApi/V1/Generated/RaiseRepair-M3SoR-v7.cs
>          public string DescriptionOfWork { get; set; }
Yes this file is the request object for the raise repair endpoint

2021-01-12 11:02 UTC, josh-dadswell-hackney commented on RepairsApi/V1/Generated/RaiseRepair-M3SoR-v7.cs
>          public string DescriptionOfWork { get; set; }
Yes this file is used by the controllers to receive the data and verify it against HACT required fields etc.

2021-01-12 11:02 UTC, kylealexanderhackney commented on RepairsApi/V1/Infrastructure/RateScheduleItem.cs
> +        public M3NHFScheduleOfRatesCodeC0 M3NHFSORCode { get; set; }
Our migrations are done based on the naming from the hact specification

2021-01-12 11:04 UTC, LBHBomotoso commented on RepairsApi.Tests/V1/Gateways/RepairGatewayTests.cs
> +            InMemoryDb.Instance.WorkOrders.Should().ContainSingle().Which.IsSameOrEqualTo(expected);
All tests are running via in memory db? 
We should try to create a postgres image to use at some opportunity.

2021-01-12 11:07 UTC, kylealexanderhackney commented on RepairsApi.Tests/V1/Gateways/RepairGatewayTests.cs
> +            InMemoryDb.Instance.WorkOrders.Should().ContainSingle().Which.IsSameOrEqualTo(expected);
running in memory for unit tests is typically preferred as it means docker is not required to run the tests and they can be done inside the IDE. the integration tests can be run against a postgres database. 
In memeory also has the benefit of not enforcing foreign key constraints so you dont have to mock large amounts of unrelated data just to run a test.

2021-01-12 11:13 UTC, LBHBomotoso commented on RepairsApi/V1/Infrastructure/AlertRegardingLocation.cs
> +    public class AlertRegardingLocation
Ok, I see

2021-01-12 11:14 UTC, LBHBomotoso commented on RepairsApi/V1/Infrastructure/RateScheduleItem.cs
> +        public M3NHFScheduleOfRatesCodeC0 M3NHFSORCode { get; set; }
I'm still working on it. I think M3NHF is an actual product also.

2021-01-12 11:14 UTC, LBHBomotoso commented on RepairsApi/V1/Generated/RaiseRepair-M3SoR-v7.cs
>          public string DescriptionOfWork { get; set; }
ok cool

2021-01-12 11:15 UTC, LBHBomotoso commented on RepairsApi.Tests/MockApiGateway.cs
> +                TenureType = $"{code}: Rnadom descirption",
Small typo

2021-01-12 11:48 UTC, josh-dadswell-hackney commented on RepairsApi/V1/Infrastructure/RateScheduleItem.cs
> +        public M3NHFScheduleOfRatesCodeC0 M3NHFSORCode { get; set; }
M3NHF is the standard of codes that can be put in through this route all other codes (including ours ones) will come through the CustomCode route

2021-01-12 12:24 UTC, LBHBomotoso approved these changes

2021-01-12 12:59 UTC, merged