401 E2E tests fix contractor acknowledge use case
LBHackney-IT/repairs-api-dotnet pull request #177
Opened 2021-04-08 12:55 UTC by LBHBomotoso

## Link to JIRA ticket

https://trello.com/c/GPKJdNkN/13-as-a-contractor-i-can-see-the-status-of-a-variation-so-that-i-know-whether-to-proceed-with-the-work-or-not

## Describe this PR

### *What is the problem we're trying to solve*

Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.

### *What changes have we introduced*

Add descriptions of what changes were made to address the problem and provide a solution.

Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

### *Follow up actions after merging PR*

Are there any next steps that need to addressed after merging this PR? Add them here.

2021-04-09 10:24 UTC, kylealexanderhackney commented on RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
> +        [Test]
These tests all look incredibly similar could we just have a mthos each test can call to run the test. or even better would be one test with the testcase attribute to add parameters to the test

2021-04-09 10:24 UTC, kylealexanderhackney commented on RepairsApi.Tests/V2/UseCase/JobStatusUpdateUseCases/ApproveVariationTests.cs
> +            (int workOrderId, Generated.JobStatusUpdateTypeCode jobStatus)
is there a reason this is on a new line. i dont have a preference but consistency is key

2021-04-12 08:01 UTC, LBHBomotoso commented on RepairsApi.Tests/V2/UseCase/JobStatusUpdateUseCases/ApproveVariationTests.cs
> +            (int workOrderId, Generated.JobStatusUpdateTypeCode jobStatus)
easier to read for me.

2021-04-12 08:02 UTC, LBHBomotoso commented on RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
> +        [Test]
The tests are composed slightly differently. Because of the way the flow works. What's mthos?

2021-04-12 08:29 UTC, kylealexanderhackney requested changes

2021-04-12 08:29 UTC, kylealexanderhackney commented on RepairsApi/V2/Gateways/JobStatusUpdateGateway.cs
> +                .LastOrDefaultAsync();
We need to order be date here. we cant leave it to chance in the DB that they are ordered by date. This will break if behaviour were added that retroactively adds updates or anything that messes with the timestamp of updates

2021-04-12 08:29 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/MoreSpecificSorUseCase.cs
> +                await Execute(workElement, workOrder);
if we need to comment to say oatch Sor codes just call the execute method PathSORCodes

2021-04-12 08:29 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/MoreSpecificSorUseCase.cs
>              var newCodes = workElement.RateScheduleItem.Where(rsi => !existingCodes.Any(ec => ec.Id == rsi.Id));
this should use original Id i believe

2021-04-12 08:29 UTC, kylealexanderhackney commented on RepairsApi/V2/Infrastructure/RateScheduleItem.cs
> +        public string OriginalId { get; set; }
this should be the same type as Id theres no reason for it to be anything else

2021-04-12 08:29 UTC, kylealexanderhackney commented on RepairsApi/V2/Factories/DBModelFactory.cs
> +                OriginalId = raiseRepair.Id
this needs to be in the if statement below as we do not know if the original Id is a valid guid we can assign

2021-04-12 08:29 UTC, kylealexanderhackney commented on RepairsApi/V2/Generated/Extensions/WorkOrderExtensions.cs
> +        public string OriginalId { get; set; }
is this used?

2021-04-12 08:39 UTC, LBHBomotoso commented on RepairsApi/V2/UseCase/JobStatusUpdatesUseCases/MoreSpecificSorUseCase.cs
> +                await Execute(workElement, workOrder);
Sorry?

2021-04-12 08:53 UTC, LBHBomotoso commented on RepairsApi/V2/Gateways/JobStatusUpdateGateway.cs
> +                .LastOrDefaultAsync();
amended

2021-04-13 13:49 UTC, LBHBomotoso commented on RepairsApi/V2/Infrastructure/RateScheduleItem.cs
> +        public string OriginalId { get; set; }
amended

2021-04-13 13:49 UTC, LBHBomotoso commented on RepairsApi/V2/Factories/DBModelFactory.cs
> +                OriginalId = raiseRepair.Id
amended

2021-04-13 13:52 UTC, LBHBomotoso commented on RepairsApi/V2/Generated/Extensions/WorkOrderExtensions.cs
> +        public string OriginalId { get; set; }
amended

2021-04-13 14:11 UTC, kylealexanderhackney approved these changes

2021-04-14 10:15 UTC, merged