Variation and workorder tasks endpoint
LBHackney-IT/repairs-api-dotnet pull request #199
Opened 2021-04-21 15:43 UTC by LBHBomotoso

## Link to JIRA ticket

https://trello.com/c/BtiMHma5/44-as-a-cm-i-can-see-a-summary-of-the-variation-request-before-submitting-it-so-i-can-clearly-see-the-details

## Describe this PR

### *What is the problem we're trying to solve*

retrieve variations in jobstatus update

### *What changes have we introduced*

new endpoint

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

### *Follow up actions after merging PR*

Increase test coverage

2021-04-22 08:10 UTC, kylealexanderhackney requested changes

2021-04-22 08:10 UTC, kylealexanderhackney commented on RepairsApi/V2/Controllers/WorkOrdersPartialController.cs
> +using Microsoft.AspNetCore.Mvc;
File name should indicate what we will find in this file as the class name cannot. Maybe WorkOrderPropertiesController if we are going with my suggestion of one file for rest calls on the WO and one file for properties on the WO

2021-04-22 08:10 UTC, kylealexanderhackney commented on RepairsApi/V2/Controllers/WorkOrdersController.cs
>      [Route("/api/v2/workOrders")]
My understanding was that when we created the partial we would move existing endpoints that hot properties of workorders like tasks and notes into the new file

2021-04-22 08:10 UTC, kylealexanderhackney commented on RepairsApi/V2/Gateways/JobStatusUpdateGateway.cs
> +        public async Task<IList<RateScheduleItem>> SelectWorkOrderVariationTasks(int workOrderId)
Variations are always on work orders so we should not have to put work order in the method name

2021-04-22 08:10 UTC, kylealexanderhackney commented on RepairsApi/V2/Gateways/JobStatusUpdateGateway.cs
> +                throw new ResourceNotFoundException($"Unable to locate jobstatus update for work order {workOrderId} with {JobStatusUpdateTypeCode._180}");
we should probably use a string instead of JobStatusUpdateTypeCode._180 so that the message means anything to a user of the system

2021-04-22 08:10 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +        private readonly IJobStatusUpdateGateway _jobStatusUpdateGateway;
whitespace between fields and ctor

2021-04-22 08:10 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +        }
empty line between methods

2021-04-22 08:10 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +            }
This should be in the response factory

2021-04-22 08:10 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +                OldQuantity = t.OriginalQuantity,
Original Quantity is not correct here if we have already varied the work order. We need to get the work and use the quantities currently on it rather than the initial values

2021-04-22 08:10 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +
This endpoint should be locked down to only be accessible if the current state fo the work order is the correct status ie pendinf approval

2021-04-22 08:10 UTC, kylealexanderhackney commented on RepairsApi/V2/Controllers/WorkOrdersPartialController.cs
> +    [ApiVersion("2.0")]
do we need to define apiversion twice

2021-04-22 08:42 UTC, LBHBomotoso commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +            }
Is it possible to override an existing extension method?

2021-04-22 08:43 UTC, LBHBomotoso commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +                OldQuantity = t.OriginalQuantity,
Please have a look at the query in the gateway.

2021-04-22 08:45 UTC, LBHBomotoso commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +
Please have a look at the query in the gateway

2021-04-22 08:46 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +            }
just give it a different name

2021-04-22 08:49 UTC, LBHBomotoso commented on RepairsApi/V2/Controllers/WorkOrdersController.cs
>      [Route("/api/v2/workOrders")]
I think it's better if you have a look and make those changes

2021-04-22 08:50 UTC, LBHBomotoso commented on RepairsApi/V2/Controllers/WorkOrdersPartialController.cs
> +using Microsoft.AspNetCore.Mvc;
amended

2021-04-22 08:52 UTC, LBHBomotoso commented on RepairsApi/V2/Boundary/Response/VariationTasksModel.cs
> +        public double? UnitCost { get; set; }
The RatescheduleItem values are nullable

2021-04-22 08:54 UTC, kylealexanderhackney requested changes

2021-04-22 08:54 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +
The query performs a check on the update type code im talking about the work order statuscode. This functionality should only be possible if the WO status is pending variation

2021-04-22 08:54 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +                OldQuantity = t.OriginalQuantity,
Maybe i am missing something but im not seeing it. Actually i was wrong before. Original Quantity will not be defined on rate schedule items that are in job status update

2021-04-22 08:56 UTC, LBHBomotoso commented on RepairsApi.Tests/MockWebApplicationFactory.cs
> -            HttpResponseMessage result = await InternalGet(uri);
The test would have to inherit from Webapplicationfactory then?

2021-04-22 08:57 UTC, kylealexanderhackney commented on RepairsApi/V2/Boundary/Response/VariationTasksModel.cs
> +        public double? UnitCost { get; set; }
Fair enough

2021-04-22 09:19 UTC, LBHBomotoso commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +            }
ok

2021-04-22 09:39 UTC, LBHBomotoso commented on RepairsApi/V2/Controllers/WorkOrdersController.cs
>      [Route("/api/v2/workOrders")]
Moved notes and tasks

2021-04-22 15:09 UTC, kylealexanderhackney commented on RepairsApi.Tests/MockWebApplicationFactory.cs
> -            HttpResponseMessage result = await InternalGet(uri);
All integration tests that call the apis should inherit from MockWEbApplicationFactory

2021-04-22 15:09 UTC, kylealexanderhackney commented on RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
> +            //workElement.RateScheduleItem.ToList()[0].Quantity
remove commented code

2021-04-23 08:31 UTC, LBHBomotoso commented on RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
> +            //workElement.RateScheduleItem.ToList()[0].Quantity
It's WIP

2021-04-23 08:33 UTC, kylealexanderhackney commented on RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
> +            //workElement.RateScheduleItem.ToList()[0].Quantity
We can t be merging WIP code into develop anymore. if its in develop theres nothing stopping it going live at any time.

2021-04-23 08:40 UTC, LBHBomotoso commented on RepairsApi.Tests/V2/E2ETests/RepairApiTests.cs
> +            //workElement.RateScheduleItem.ToList()[0].Quantity
Ok

2021-04-23 08:43 UTC, kylealexanderhackney commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +            foreach (var task in variationTasks)
this would look a lot cleaner usinf linq join

something of the form 
 workordertasks.join(variationtasks, vtask => wtask.id, wtask.originalId, (vtask, wtask) => <transform to return type>)
should do it

2021-04-23 08:53 UTC, LBHBomotoso commented on RepairsApi/V2/UseCase/ListVariationTasksUseCase.cs
> +            foreach (var task in variationTasks)
Does it return the right data?

2021-04-27 14:47 UTC, josh-dadswell-hackney approved these changes

2021-04-27 14:47 UTC, josh-dadswell-hackney commented on RepairsApi.Tests/Helpers/ObjectExtensions.cs
> +        /// For Loading Nvaigation Properties in tests
typo

2021-04-27 14:47 UTC, josh-dadswell-hackney commented on RepairsApi.Tests/V2/E2ETests/Repairs/VariationApprovalTests.cs
> +        [Test]
could be refactored into test cases?

2021-04-27 14:55 UTC, josh-dadswell-hackney requested changes

2021-04-27 14:55 UTC, josh-dadswell-hackney commented on RepairsApi.Tests/V2/E2ETests/Repairs/VariationApprovalTests.cs
> +        public async Task WorkOrderRejectVariation()
not quite need to pass in the things as params and use them ;)

2021-04-27 16:08 UTC, josh-dadswell-hackney approved these changes

2021-04-27 16:09 UTC, merged