Use "Variation Pending Approval"
LBHackney-IT/repairs-api-dotnet pull request #205
Opened 2021-04-22 13:50 UTC by alex-demetriou

## [Trello: As a contract manager, I can see if a request is variation pending approval, so that I know which repairs to approve](https://trello.com/c/uWW6pSKg)

 - Changes *Pending Approval* to *Variation Pending Approval* in `WorkOrderStatus`.
 - Changes *Pending Authorisation* to *Variation Pending Authorisation* in `WorkOrderReason`.

2021-04-22 14:38 UTC, LBHBomotoso approved these changes

2021-04-22 15:03 UTC, kylealexanderhackney approved these changes

2021-04-22 15:14 UTC, kylealexanderhackney requested changes

2021-04-22 15:14 UTC, kylealexanderhackney commented on RepairsApi/V2/Boundary/Response/WorkOrderListItem.cs
> +        public const string PendApp = "Variation Pending Approval";
WE should change the variable names also in my opinion.
Potentially even the work status enum. as long as the number stays the saem there should be no problem  but the variable names should reflect the fact its specifically for variations as well

2021-04-27 09:32 UTC, alex-demetriou commented on RepairsApi/V2/Boundary/Response/WorkOrderListItem.cs
> +        public const string PendApp = "Variation Pending Approval";
Cheers - that's a good point!
I've pushed these changes now

2021-04-27 09:33 UTC, kylealexanderhackney approved these changes

2021-04-27 09:53 UTC, merged