Company tmo table
LBHackney-IT/repairs-api-dotnet pull request #248
Opened 2021-05-12 11:06 UTC by elena-evans

## Link to JIRA ticket

https://trello.com/c/dVNIA7Ky/118-as-a-user-i-can-see-if-this-is-a-tmo-property-so-that-repairs-are-not-raised-in-error

## Describe this PR

### *What is the problem we're trying to solve*

Added class for TMO company table and migration

### *What changes have we introduced*

Created lookup table for TMO data

Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

### *Follow up actions after merging PR*

Load data into tables

2021-05-12 11:12 UTC, josh-dadswell-hackney commented on RepairsApi/V2/Infrastructure/Migrations/20210512104555_TMOCompanyTable.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
In order for EFCore to know to create the table the new type must be referenced either by another object in the DB or manually setup in the database context.

There is a simple example here: https://www.entityframeworktutorial.net/efcore/entity-framework-core-dbcontext.aspx#:~:text=The%20DbContext%20class%20is%20an,Of%20Work%20and%20Repository%20patterns.

Also when generating a new Migration be sure to remove that empty one first

2021-05-12 11:12 UTC, josh-dadswell-hackney requested changes
Migration incomplete

2021-05-12 11:19 UTC, kylealexanderhackney commented on RepairsApi/V2/Infrastructure/Migrations/20210512104555_TMOCompanyTable.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
Simplest would be to add a dbset for this object

2021-05-12 11:20 UTC, kylealexanderhackney commented
Is there a reason the work required for TMO's cant be done in tandem with this and just merge the feature in complete

2021-05-12 11:21 UTC, kylealexanderhackney requested changes

2021-05-12 11:21 UTC, kylealexanderhackney commented on RepairsApi/V2/Infrastructure/Company.cs
> +        [StringLength(10)]
missing setup for a key. AFAIK the CoCode needs a [Key] attribute if its is the primary key

2021-05-12 11:23 UTC, kylealexanderhackney commented on RepairsApi/V2/Infrastructure/Company.cs
> +        public bool CoEnabled { get; set; }
I believe primitives are created as non nullable by ef core unless they are marked as nullable (eg bool?)

does this line up with the data we will be migrating in?

2021-05-13 11:39 UTC, LBHBomotoso commented on RepairsApi/V2/Infrastructure/Migrations/20210512104555_TMOCompanyTable.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
Yes, forgot to add the dbset. Will be added

2021-05-13 11:42 UTC, LBHBomotoso commented on RepairsApi/V2/Infrastructure/Company.cs
> +        [StringLength(10)]
we can make it unique

2021-05-13 11:43 UTC, LBHBomotoso commented on RepairsApi/V2/Infrastructure/Company.cs
> +        public bool CoEnabled { get; set; }
yes it does, thanks

2021-05-14 08:33 UTC, kylealexanderhackney commented on RepairsApi/V2/Infrastructure/Company.cs
> +        [StringLength(10)]
It will need to be unique if we are going ot mark it as the primary key

2021-05-14 15:11 UTC, kylealexanderhackney requested changes

2021-05-14 15:11 UTC, kylealexanderhackney commented on RepairsApi/V2/Infrastructure/Migrations/20210514143056_TMOCompanyTable.cs
> +        {
a migration runs it is these methods that change the db. if they are empty no change will occur to the database. for what you are doing i would expect to see something similar to https://github.com/LBHackney-IT/repairs-api-dotnet/blob/develop/RepairsApi/V2/Infrastructure/Migrations/20201210131629_AddRateScheduleItem.cs
it seems everything is setup right the migration itself just needs to be removed and readded via the cli

2021-05-17 14:43 UTC, kylealexanderhackney approved these changes

2021-05-17 15:19 UTC, merged