Add tmo data to property object response
LBHackney-IT/repairs-api-dotnet pull request #264
Opened 2021-05-25 09:35 UTC by elena-evans

## Link to JIRA ticket

https://trello.com/c/v5YU3xU8/99-check-all-tmo-properties-are-listed-correctly

## Describe this PR

### *What is the problem we're trying to solve*

added TMO to property model

### *What changes have we introduced*

added TMO to property model and tests for this

Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

### *Follow up actions after merging PR*

Are there any next steps that need to addressed after merging this PR? Add them here.

2021-05-25 10:45 UTC, kylealexanderhackney requested changes

2021-05-25 10:45 UTC, kylealexanderhackney commented on .editorconfig
> +dotnet_diagnostic.CS8602.severity = none
We shouldnt supress this its a useful feature for understanding when a variable will be null

2021-05-25 10:45 UTC, kylealexanderhackney commented on RepairsApi.Tests/V2/Gateways/PropertyGatewayTests.cs
>  using RepairsApi.V2.Exceptions;
Can we put some tests in here to check a "happy path". IE it does match a TMO and we see that TMO in the object

2021-05-25 13:58 UTC, elena-evans commented on .editorconfig
> +dotnet_diagnostic.CS8602.severity = none
We tried avoiding triggering this rule in the code by changing it to
`string? tmo = _repairsContext.Company.Where(c => c.CoCode.Equals(response.Content.CompAvail))                .SingleOrDefault()?.Name;`
but it still triggered it. Do you have an idea for how else we could avoid that?

2021-05-26 11:55 UTC, kylealexanderhackney commented on .editorconfig
> +dotnet_diagnostic.CS8602.severity = none
response.Content!.CompAvail will do it. its complaining because response.Content is not guaranteed to not be null. There is a success check above this code so we can use the exclamation mark to tell the compile to ignore the rule in this statement

2021-05-26 13:36 UTC, elena-evans commented on .editorconfig
> +dotnet_diagnostic.CS8602.severity = none
Thanks Kyle, I changed it to that and it was happy!

2021-05-26 13:37 UTC, elena-evans commented on RepairsApi.Tests/V2/Gateways/PropertyGatewayTests.cs
>  using RepairsApi.V2.Exceptions;
We've added this in now

2021-05-27 12:56 UTC, josh-dadswell-hackney requested changes

2021-05-27 12:56 UTC, josh-dadswell-hackney commented on RepairsApi.Tests/V2/Gateways/PropertyGatewayTests.cs
> +
whitespace

2021-05-27 12:56 UTC, josh-dadswell-hackney commented on .editorconfig
> +
should revert these before commiting

2021-05-27 12:56 UTC, josh-dadswell-hackney commented on RepairsApi.Tests/TestDataSeeder.cs
> +
needless whitespace

2021-05-27 12:56 UTC, josh-dadswell-hackney commented on RepairsApi.Tests/V2/Gateways/PropertyGatewayTests.cs
> +        [TestCase("001", "TMO Name1")]
Usually reserve multiple test cases for testing different parts of the code, this looks like the extra tests arent adding any value so are not worth the execution time

2021-05-27 12:56 UTC, josh-dadswell-hackney commented on RepairsApi.Tests/V2/Gateways/PropertyGatewayTests.cs
> +                new Company {CoCode = "001", CompAvail = "001", Description = "TMO Address1", Name = "TMO Name1" },
should hold the test data somewhere central (class variable) so that you dont have magic strings here and in tests e.g. "001" etc.

2021-05-27 12:56 UTC, josh-dadswell-hackney commented on RepairsApi.Tests/V2/UseCase/GetPropertyUseCaseTests.cs
>              var expectedPersonAlerts = new PersonAlertList() { Alerts = StubAlerts().Generate(5) };
magic strings should be in vars

2021-05-27 12:56 UTC, josh-dadswell-hackney commented on RepairsApi/V2/Gateways/Models/PropertyApiResponse.cs
>          public short NoDoubleBeds { get; set; }
I know its not all from this PR but why is there this commented out code? Should not leave stuff like this in the code base as its confusing

2021-06-02 11:35 UTC, kylealexanderhackney approved these changes

2021-06-02 15:08 UTC, josh-dadswell-hackney approved these changes

2021-06-02 15:10 UTC, merged