Multi trade workorders
LBHackney-IT/repairs-api-dotnet pull request #627
Opened 2022-02-25 14:37 UTC by LBHCallumM

## Link to JIRA ticket

[Story](https://www.pivotaltracker.com/story/show/181056484)

## Work To Do

Still waiting to see spreadsheet containing all SOR codes. I need the codes to complete the migration.

## Describe this PR

Allow a user to vary a workOrder with SOR codes from multiple trades. 

The list below contains which trades should be related to which.
https://docs.google.com/spreadsheets/d/1ebsVMmyrjwqfRGFGI0JTOnT7uD5Qf40-UP53sZm1I3E/edit#gid=1367481187

===

- Added the table 'RelatedTrade' to link between a primary trade, and its related trades
- Additional trades should only be shown when varying a workOrder. I have added the property `showAdditionalTrades` to the request object.

Request object:
```
{
  propertyReference: "",
  contractorReference : "",
  isRaisable : false,
  showAdditionalTrades : false
}
```

Affected endpoints:
`/api/schedule-of-rates/codes`

The changes won't need a feature toggle, because the property `showAdditionalTrades` in the request defaults to false.

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

2022-02-25 16:26 UTC, teodor-hristoforov-hackney approved these changes

2022-03-01 14:09 UTC, Asura5 commented on RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
> +            var request = new ListScheduleOfRatesRequest
DRY - extract to a helper method (even within the same class)

2022-03-01 14:13 UTC, Asura5 commented on RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
> +            var request = new ListScheduleOfRatesRequest
As above

2022-03-01 14:13 UTC, Asura5 commented on RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
> +            var request = new ListScheduleOfRatesRequest
As above

2022-03-01 14:14 UTC, Asura5 commented on RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
> +            var request = new ListScheduleOfRatesRequest
As above

2022-03-01 14:14 UTC, Asura5 commented on RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
> +            var request = new ListScheduleOfRatesRequest
As below

2022-03-01 14:15 UTC, Asura5 commented on RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
> +                ShowAdditionalTrades = true,
shouldn't this be false?

2022-03-01 14:15 UTC, Asura5 commented on RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
> +            response.Should().HaveCount(primaryTradeSorCodes.Count);
Add a check that there are no codes from other trades

2022-03-01 14:16 UTC, Asura5 commented on RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
> +            response.Should().HaveCount(primaryTradeSorCodes.Count);
If this is the test for not showing related trades - Add a check that there are no codes from other trades

2022-03-01 14:16 UTC, Asura5 commented on RepairsApi.Tests/V2/Gateways/ScheduleOfRatesGatewayTests.cs
> +            var request = new ListScheduleOfRatesRequest
Could be in the helper described earlier

2022-03-01 14:28 UTC, Asura5 requested changes
See comments

2022-03-01 15:32 UTC, LBHCallumM commented
> See comments

Thanks. I have created a helper method to build the request object, and refactored any code that is reused.

2022-03-03 13:08 UTC, Asura5 approved these changes

2022-03-03 13:09 UTC, merged