Update GoogleSheetMapper to programatically load more records
LBHackney-IT/repairs-api-dotnet pull request #630
Opened 2022-02-28 16:39 UTC by LBHCallumM

## Describe this PR

Updates to the LegalDisrepair integration.

To make sure all legalDisrepair records are loaded, I have added a mechanism the loads the first 500, then if the last 10 rows arent empty, loads the next 500. This approach means we can load the least number of records, while ensuring all records are loaded.

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

2022-03-01 14:29 UTC, Asura5 commented on RepairsApi.Tests/V2/Services/GoogleSheets/LegalDisrepairMapperTests.cs
> +        private Mock<IGoogleSheetGateway<LegalDisrepairCredentials>> _mockGateway;
Reusability: Does this have to be LegalDisrepairCredentials, or can it be GoogleSheetCredentials

2022-03-01 14:31 UTC, Asura5 commented on RepairsApi/Startup.cs
> +                new GoogleSheetGateway<LegalDisrepairCredentials>(ConfigureSheetsService(options.LegalDisrepairCredentials), legalDisrepairCredentials, new LoggerFactory()));
Code smell - line 234+238 could do with a refactor - you are using options.LegalDisrepairSpreadsheetId both directly and indirectly

2022-03-01 14:32 UTC, Asura5 requested changes
See comments

2022-03-01 15:34 UTC, LBHCallumM commented on RepairsApi.Tests/V2/Services/GoogleSheets/LegalDisrepairMapperTests.cs
> +        private Mock<IGoogleSheetGateway<LegalDisrepairCredentials>> _mockGateway;
The intention was to make dependency injection easier. Lets discuss this in tomorrows dropin session .

2022-03-02 15:18 UTC, LBHCallumM commented on RepairsApi/Startup.cs
> +                new GoogleSheetGateway<LegalDisrepairCredentials>(ConfigureSheetsService(options.LegalDisrepairCredentials), legalDisrepairCredentials, new LoggerFactory()));
> See comments

I have removed the `IGoogleSheetCredentials` interface from GoogleSheetGateway.

2022-04-28 08:13 UTC, closed without merging